apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
- https://github.com/kubeflow/manifests.git/pipeline/upstream/base/application?ref=v1.2-branch
- https://github.com/kubeflow/manifests.git/pipeline/upstream/base/pipeline?ref=v1.2-branch
- https://github.com/kubeflow/manifests.git/pipeline/upstream/base/metadata?ref=v1.2-branch
- https://github.com/kubeflow/manifests.git/pipeline/upstream/base/cache?ref=v1.2-branch
- https://github.com/kubeflow/manifests.git/pipeline/upstream/base/cache-deployer?ref=v1.2-branch
configMapGenerator:
- name: pipeline-install-config
  envs: ["params.env"]
secretGenerator:
- name: mysql-secret
  envs: ["params-db-secret.env"]
vars:
- name: kfp-namespace
  objref:
    kind: Deployment
    apiVersion: apps/v1
    name: ml-pipeline
  fieldref:
    fieldpath: metadata.namespace
- name: kfp-app-name
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.appName
- name: kfp-app-version
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.appVersion
- name: kfp-artifact-bucket-name
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.bucketName
configurations:
- params.yaml
