apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
- ../../env/platform-agnostic
configMapGenerator:
- name: pipeline-install-config
  envs: ["params.env"]
  behavior: merge
- name: workflow-controller-configmap
  behavior: replace
  files:
  - config
- name: ml-pipeline-ui-configmap
  behavior: replace
  files:
  - viewer-pod-template.json
# secretGenerator:
# - name: mysql-secret
#   envs: ["secret.env"]
#   behavior: delete
# - name: mlpipeline-minio-artifact
#   envs: ["minio-artifact-secret-patch.env"]
#   behavior: delete
generatorOptions:
  disableNameSuffixHash: false
patchesStrategicMerge:
- aws-configuration-patch.yaml
# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines
