"apiVersion": "v1"
"data":
  "password": "KMS_ENC:AQICAHhueeLxVF2M5hjc1Dab/ZBGw8RRJ0J0eD2kr2DdBZljegFe/L2yOGcwcwDINIj3E4iEAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSL7tIdYHH0wvbtX+AgEQgCufapH42pxbcuaz77S2RdyDx55ZX6kpScQwe46ololWaGAZ1+Gt6c1x2PRj:"
  "username": "cm9vdHVzZXI="
"kind": "Secret"
"metadata":
  "name": "mysql-secret"
  "namespace": "demo"
"type": "Opaque"
