apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-roles
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    targetRevision: v1.2-branch
    path: kubeflow-roles/base
    kustomize: {}
