apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
nameprefix: application-controller-
commonLabels:
  app.kubernetes.io/component: kubeflow
  app.kubernetes.io/name: kubeflow
resources:
- https://github.com/kubeflow/manifests.git/application/application-crds/base?ref=v1.2-branch
- https://github.com/kubeflow/manifests.git/application/application/base?ref=v1.2-branch
images:
- name: gcr.io/kubeflow-images-public/kubernetes-sigs/application
  newName: gcr.io/kubeflow-images-public/kubernetes-sigs/application
  newTag: 1.0-beta