apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- https://github.com/kubeflow/pipelines.git/manifests/kustomize/base/application?ref=1.4.0-rc.1
- https://github.com/kubeflow/pipelines.git/manifests/kustomize/base/pipeline?ref=1.4.0-rc.1
- https://github.com/kubeflow/pipelines.git/manifests/kustomize/base/metadata?ref=1.4.0-rc.1
- https://github.com/kubeflow/pipelines.git/manifests/kustomize/base/cache?ref=1.4.0-rc.1
- https://github.com/kubeflow/pipelines.git/manifests/kustomize/base/cache-deployer?ref=1.4.0-rc.1
configMapGenerator:
- name: pipeline-install-config
  literals:
    - dbHost=YOUR_RDS_ENDPOINT
    - bucketName=YOUR_S3_BUCKET_NAME
    - minioServiceHost=s3.amazonaws.com
    - minioServiceRegion=YOUR_AWS_REGION
    - autoUpdatePipelineDefaultVersion=true
    - cronScheduleTimezone=UTC
generatorOptions:
  disableNameSuffixHash: true
patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ml-pipeline-ui
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env
      value:
        - name: ALLOW_CUSTOM_VISUALIZATIONS
          value: "true"
